### ISSUE TITLE
README: Which GCP services are required?

### ISSUE THREAD

**Issue by fmorisan** [HyphalDAO/Hyphal-dApp#27]
Hi, I'm looking into this project and trying to set it up (at least locally). My understanding is that I need Firebase account details, but GCP seems to have split these into different APIs. It would be great if anyone could tell me which services from the Cloud Console are needed, since it's a bit confusing for someone who isn't used to Google's platform. Thanks!

P.S. I'm willing to submit a PR to update the README with whatever information you can throw my way :)

**Comment by mudrila** [comment]
Hey Filipp
Basically, we're using only Firebase, no other GCP products. 

You need to set up a Firebase account, enable Authentication, create Firestore, make sure that your Storage is also enabled, and deploy cloud functions - https://github.com/HyphalDAO/hyphal-cloud-functions.

That should be pretty much it - let me know if you have further questions.
P.S. PR with updating README is welcome 😃

**Comment by Koochr** [comment]
> Hey Filipp Basically, we're using only Firebase, no other GCP products.
> 
> You need to set up a Firebase account, enable Authentication, create Firestore, make sure that your Storage is also enabled, and deploy cloud functions - https://github.com/HyphalDAO/hyphal-cloud-functions.
> 
> That should be pretty much it - let me know if you have further questions. P.S. PR with updating README is welcome smiley

Not exactly. You also need firebase functions.
Here is the repo: https://github.com/HyphalDAO/hyphal-cloud-functions

You can clone the repo, add `.firebaserc` file (gitignored, take this one as an example and change the project name: https://github.com/HyphalDAO/hyphal-cloud-functions/blob/master/.firebaserc-sample), set up firebase-cli and deploy functions.

Also you will need to set up firebase access rules, just copy-paste this file:
https://github.com/HyphalDAO/hyphal-cloud-functions/blob/master/rules_sample.txt

We apologize the lack of user-friendly documentation, however, this should be enough, the rest of instructions you can find in official firebase docs.

Please let me know if I missed something.
