### ISSUE TITLE
DAO Dashboard - Create Proposal - Linear Voting Proposals - Fix UI to follow new design (layout, input fields, and proposal types)

### ISSUE THREAD

**Issue by happykaito** [HyphalDAO/Hyphal-dApp#35]

**Comment by Koochr** [comment]
@happykaito is this issue still actual? I've added multiple actions, please check.
The design we have is a bit irrelevant since we can't create multiple proposals for multiple strategies at once. We can attach several transactions to each proposal, so I've made it a bit differently

**Comment by Koochr** [comment]
@happykaito I'm closing this since it seems actual. Please reopen if something is wrong
