### ISSUE TITLE
feat: Batched transactions

### ISSUE THREAD

**Issue by nginnever** [HyphalDAO/Hyphal-dApp#4]
Info:
Currently we create a separate metamask transaction for each step of a multi-execution operations. 

feature:
We can create a preview display of the transactions that will be batch signed and send all of them to a proxy contract to execute at once, this will save gas and improve UX throughout the site.

examples:
See gnosis safe app for examples of how this can be done

**Comment by big-javascript-fan** [comment]
@nginnever  This is kind of good solution. I think here, it is required to build proxy contract which will get signed message from frontend and execute all of them at once. and just make one smart contract call,
But for permission wise, this proxy contract need to have smart contract role to others.
Is this what you can provide, right?
