### ISSUE TITLE
DAO List Duplicates

### ISSUE THREAD

**Issue by nginnever** [HyphalDAO/Hyphal-dApp#44]
Occasionally the list of DAOs will be duplicated when navigating to the DAOs page

**Comment by Koochr** [comment]
I tried this and couldn't reproduce. This can happen only in local deployment with react hot module reload, when you change some page contents, but not in production.

**Comment by nginnever** [comment]
This is still an issue, it happens on production site only

**Comment by Koochr** [comment]
Oh yeah, was my bad, fixed it now
