### ISSUE TITLE
Create Proposal should be visible to non-admins

### ISSUE THREAD

**Issue by nginnever** [HyphalDAO/Hyphal-dApp#51]
Currently only admins can create proposals for a DAO, but this should be open to the public first, and only restricted if we build features for it

**Comment by Koochr** [comment]
@nginnever I will make it visible if there's a strategy connected, and leave creating admin proposals for admins only, is it ok?

**Comment by nginnever** [comment]
I don't see a good reason to restrict creating proposals to only admins at all. If it is easier because of the way you currently have things permissioned in the components then that is fine for now.
