### ISSUE TITLE
"Please connect wallet" placeholder

### ISSUE THREAD

**Issue by Koochr** [HyphalDAO/Hyphal-dApp#60]
In some cases we need to display something like this, e.g. if you go to "create proposal" page and your wallet is not connected

**Comment by nginnever** [comment]
I have linked this multiple times now, this is a standard for how dApps handle wallet connection

https://github.com/Web3Modal/web3modal

Also review other dApps and explore how they handle this

gnosis, uniswap, opensea, etc

**Comment by Koochr** [comment]
@nginnever  I've implemented web3-modal. I've skipped some wallet options which required api keys, I can add them if you provide them.
But the issue was about another thing, we still need to display something instead of the form if user without a connected wallet goes to the page like "create proposal".
It can be a warning like "please connect modal" and a "connect wallet" button, but I need a design.
Also I need a design of the "wrong network" placeholder for network checker.

**Comment by nginnever** [comment]
>Also review other dApps and explore how they handle this

for example, on create proposal, simply change "create proposal" to "connect wallet". Nothing more.

>Also I need a design of the "wrong network" placeholder for network checker.

The way we functionally handle wrong network (block everything) is not what I want, we will build a network switcher just like uniswap and gnosis
