### ISSUE TITLE
Expand DAO should be visible to everyone

### ISSUE THREAD

**Issue by nginnever** [HyphalDAO/Hyphal-dApp#61]
Just like create proposal, anyone can initiate the expansion of a DAO

**Comment by Koochr** [comment]
> Just like create proposal, anyone can initiate the expansion of a DAO

We have an issue here.
Only one "expand DAO" proposal can be created for all the time. And on the proposals page we cannot even see the strategies and their parameters. It's not only related to this issue, but imagine the situation when some passer-by initiates expanding DAO with a bunch of strategies which DAO members don't wish. And we don't have any option to delete/reject this proposal and re-initiate expanding DAO with some other set of strategies. We need to handle it in some way

**Comment by nginnever** [comment]
>Only one "expand DAO" proposal can be created for all the time.

DAOs can be expanded and contracted at anytime, this is the fundamental purpose of this DAO platform. 

>It's not only related to this issue, but imagine the situation when some passer-by initiates expanding DAO with a bunch of strategies which DAO members don't wish.

Open it to the public, anyone can create proposals, it does not mean that anyone has to vote on proposals

>And we don't have any option to delete/reject this proposal and re-initiate expanding DAO with some other set of strategies. We need to handle it in some way

There is never a need to delete proposals (unless you are talking about a security against bribe attacks which you are not).

We are building Expand DAO to be able to select which voting strategy is to handle the expansion (or removal). You should prepare your logic to not always assume that expanding a DAO goes to the admin proposals
