### ISSUE TITLE
Remove signing timeout

### ISSUE THREAD

**Issue by nginnever** [HyphalDAO/Hyphal-dApp#64]
We have some timeout in the firebase api. This should be fine and require users to reconnect their wallet, but it should not ask them to re-sign each time.

Refer to other dApps to see how this is done

**Comment by Koochr** [comment]
Not sure this can be done. Other dApps probably just don't use firebase. We use this signature as a token and cannot avoid resigning it each time it expires. The only way how we can do that is to create "eternal" token, but this would be a serious security issue.
